// loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// login
export const LANDING_CHANGE_STATE = 'LANDING_CHANGE_STATE';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_CHANGE_STATE = 'LOGIN_CHANGE_STATE';

// signUp
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_LOADING_ENDED = 'SIGNUP_LOADING_ENDED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_CHANGE_STATE = 'SIGNUP_CHANGE_STATE';

// signUp Maahir
export const MAAHIR_SIGNUP_REQUEST = 'MAAHIR_SIGNUP_REQUEST';
export const MAAHIR_SIGNUP_RESPONSE = 'MAAHIR_SIGNUP_RESPONSE';
export const MAAHIR_SIGNUP_FAILED = 'MAAHIR_SIGNUP_FAILED';
export const MAAHIR_SIGNUP_CHANGE_STATE = 'MAAHIR_SIGNUP_CHANGE_STATE';

//services
export const SERVICE_REQUEST = 'SERVICE_REQUEST';
export const SERVICE_RESPONSE = 'SERVICE_RESPONSE';
export const SERVICE_LOADING_ENDED = 'SERVICE_LOADING_ENDED';
export const SERVICE_FAILED = 'SERVICE_FAILED';
export const SERVICE_CHANGE_STATE = 'SERVICE_CHANGE_STATE';

//services by Location
export const SERVICE_BY_LOCATION_REQUEST = 'SERVICE_BY_LOCATION_REQUEST';
export const SERVICE_BY_LOCATION_RESPONSE = 'SERVICE_BY_LOCATION_RESPONSE';
export const SERVICE_BY_LOCATION_FAILED = 'SERVICE_BY_LOCATION_FAILED';
export const SERVICE_BY_LOCATION_LOADING_ENDED = 'SERVICE_BY_LOCATION_LOADING_ENDED';
export const SERVICE_BY_LOCATION_CHANGE_STATE = 'SERVICE_BY_LOCATION_CHANGE_STATE';

//forgot password
export const FORGOT_REQUEST = 'FORGOT_REQUEST';
export const FORGOT_RESPONSE = 'FORGOT_RESPONSE';
export const FORGOT_FAILED = 'FORGOT_FAILED';
export const FORGOT_LOADING_ENDED = 'FORGOT_LOADING_ENDED';
export const FORGOT_CHANGE_STATE = 'FORGOT_CHANGE_STATE';

//reset password
export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_RESPONSE = 'RESET_RESPONSE';
export const RESET_FAILED = 'RESET_FAILED';
export const RESET_LOADING_ENDED = 'RESET_LOADING_ENDED';
export const RESET_CHANGE_STATE = 'RESET_CHANGE_STATE';

//Maahir detail profile screen
export const MAAHIR_DETAIL_REQUEST = 'MAAHIR_DETAIL_REQUEST';
export const MAAHIR_DETAIL_RESPONSE = 'MAAHIR_DETAIL_RESPONSE';
export const MAAHIR_DETAIL_FAILED = 'MAAHIR_DETAIL_FAILED';

export const MAAHIR_BOOK_REQUEST = 'MAAHIR_BOOK_REQUEST';
export const MAAHIR_BOOK_RESPONSE = 'MAAHIR_BOOK_RESPONSE';
export const MAAHIR_BOOK_FAILED = 'MAAHIR_BOOK_FAILED';

export const MAAHIR_DETAIL_LOADING_ENDED = 'MAAHIR_DETAIL_LOADING_ENDED';
export const MAAHIR_DETAIL_CHANGE_STATE = 'MAAHIR_DETAIL_CHANGE_STATE';

// Maahir Appointment Detail screen
export const MAAHIR_APPOINTMENT_DETAIL_REQUEST = 'MAAHIR_APPOINTMENT_DETAIL_REQUEST';
export const MAAHIR_APPOINTMENT_DETAIL_RESPONSE = 'MAAHIR_APPOINTMENT_DETAIL_RESPONSE';
export const MAAHIR_APPOINTMENT_DETAIL_FAILED = 'MAAHIR_APPOINTMENT_DETAIL_FAILED';
export const MAAHIR_APPOINTMENT_DETAIL_CHANGE_STATE = 'MAAHIR_APPOINTMENT_DETAIL_CHANGE_STATE';

export const REJECT_APPOINTMENT_REQUEST = 'REJECT_APPOINTMENT_REQUEST';
export const REJECT_APPOINTMENT_RESPONSE = 'REJECT_APPOINTMENT_RESPONSE';
export const REJECT_APPOINTMENT_FAILED = 'REJECT_APPOINTMENT_FAILED';

export const APPROVE_APPOINTMENT_REQUEST = 'APPROVE_APPOINTMENT_REQUEST';
export const APPROVE_APPOINTMENT_RESPONSE = 'APPROVE_APPOINTMENT_RESPONSE';
export const APPROVE_APPOINTMENT_FAILED = 'APPROVE_APPOINTMENT_FAILED';

//logout
export const LOG_OUT = 'LOG_OUT';